name: swagger

on:
  push:
    tags:
      - "*"

permissions: 
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: "^1.20.0"
      - uses: actions/checkout@v3
      - name: Generate swagger specification
        run: |
          make spec
          ./s21adapter_spec > swagger.json
      - uses: ncipollo/release-action@v1.13.0
        with:
          artifacts: swagger.json
